# Generated by Django 4.1.7 on 2023-02-23 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Задание',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('создал', models.CharField(blank=True, max_length=255)),
                ('содержание', models.CharField(blank=True, max_length=1000)),
                ('отвественный', models.CharField(blank=True, max_length=255)),
                ('дата_создания', models.CharField(blank=True, max_length=255)),
                ('дата_выполения', models.CharField(blank=True, max_length=255)),
                ('срок', models.CharField(blank=True, max_length=255)),
                ('отчет', models.CharField(blank=True, max_length=255)),
                ('файл', models.FileField(blank=True, max_length=255, upload_to='')),
            ],
        ),
    ]
