# Generated by Django 4.1.7 on 2023-02-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='задание',
            old_name='файл',
            new_name='файл_выполнения',
        ),
        migrations.AddField(
            model_name='задание',
            name='состояние',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='задание',
            name='файл_выполнения_резерв',
            field=models.FileField(blank=True, max_length=255, upload_to=''),
        ),
        migrations.AddField(
            model_name='задание',
            name='файл_задания',
            field=models.FileField(blank=True, max_length=255, upload_to=''),
        ),
        migrations.AddField(
            model_name='задание',
            name='файл_задания_резерв',
            field=models.FileField(blank=True, max_length=255, upload_to=''),
        ),
    ]
