# Generated by Django 4.1.7 on 2023-02-24 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_файл_задание_файл_выполнения_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='задание',
            name='дата_последних_изменений',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
