# Generated by Django 4.1.7 on 2023-02-24 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_задание_дата_последних_изменений'),
    ]

    operations = [
        migrations.RenameField(
            model_name='задание',
            old_name='состояние',
            new_name='статус',
        ),
    ]
