# Generated by Django 4.1.7 on 2023-02-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_состояние_задание_статус'),
    ]

    operations = [
        migrations.AlterField(
            model_name='задание',
            name='файл_задания',
            field=models.FileField(upload_to=''),
        ),
    ]
