# Generated by Django 4.1.7 on 2023-03-04 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_customer_order_organization_research_delete_router_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='research',
            name='organization',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
        migrations.DeleteModel(
            name='Research',
        ),
    ]
