# Generated by Django 4.1.7 on 2023-03-04 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_order_customer_remove_order_organization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ivan_Mazur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
