# Generated by Django 4.1.7 on 2023-03-05 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_ivan_mazur'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Задание',
            new_name='Задания',
        ),
        migrations.AddField(
            model_name='ivan_mazur',
            name='задание',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='задание', to='core.задания'),
        ),
    ]
