# Generated by Django 4.1.7 on 2023-03-05 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_задание_задания_ivan_mazur_задание'),
    ]

    operations = [
        migrations.CreateModel(
            name='Katya_Sidorina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work', to='core.задания')),
            ],
        ),
        migrations.CreateModel(
            name='Dima_Vinokurov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task', to='core.задания')),
            ],
        ),
    ]
