# Generated by Django 4.1.7 on 2023-08-22 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_taskfile_file_taskfile_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to='report_files/'),
        ),
        migrations.AddField(
            model_name='task',
            name='report_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
